#!/usr/bin/env bash

# This script must be executed on the machine where the user is to notify

USER="livia"
UID=$(id -u "$USER")

DISPLAY=":0"
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID/bus"

if [ $# -eq 0 ]; then
  echo "Usage: $0 <message> [body]"
  exit 1
fi

sudo -u "$USER" \
  DISPLAY="$DISPLAY" \
  DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" \
  notify-send "$@"

