#!/usr/bin/env bash

# This script must be executed on the machine where the user is to notify

TARGET_USER="livia"
USER_UID=$(id -u "$TARGET_USER")

DISPLAY=":0"
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$USER_UID/bus"

if [ $# -eq 0 ]; then
  echo "Usage: $0 <summary> [body]"
  exit 1
fi

sudo -u "$TARGET_USER" \
  DISPLAY="$DISPLAY" \
  DBUS_SESSION_BUS_ADDRESS="$DBUS_SESSION_BUS_ADDRESS" \
  notify-send "$@"
